FROM php:7.4-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql \
    && a2enmod rewrite

RUN printf '%s\n' \
    '<VirtualHost *:80>' \
    '    ServerName 127.0.0.1' \
    '    DocumentRoot /var/www/html' \
    '    SetEnv CI_ENV development' \
    '    <Directory /var/www/html>' \
    '        AllowOverride All' \
    '        Require all granted' \
    '    </Directory>' \
    '</VirtualHost>' \
    > /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html
